# Research-Grade Federated HuBERT Distillation Configuration
# Methodology perfectly aligned with pretraining implementation
distillation:
  # Teacher model configuration (pre-trained HuBERT base - matching pretraining)
  teacher_hidden_size: 768
  teacher_intermediate_size: 3072
  teacher_num_attention_heads: 12
  teacher_num_hidden_layers: 12
  teacher_vocab_size: 504
  
  # Student model configuration (smaller model to train - matching pretraining architecture)
  student_hidden_size: 384  # Smaller than teacher (matching pretraining scale)
  student_intermediate_size: 1536  # Smaller than teacher (matching pretraining scale)
  student_num_attention_heads: 6   # Smaller than teacher (matching pretraining scale)
  student_num_layers: 6     # Smaller than teacher (matching pretraining scale)
  vocab_size: 504
  
  # Training configuration - Optimized for resource utilization (matching pretraining)
  batch_size: 16  # Increased for better GPU utilization and training efficiency (matching pretraining)
  local_epochs: 10  # Reduced to match pretraining for federated efficiency
  learning_rate: 5e-4  # Same learning rate as pretraining for consistency
  weight_decay: 0.01
  max_grad_norm: 1.0
  
  # Distillation specific parameters
  temperature: 4.0  # Temperature for soft targets
  alpha: 0.7        # Weight for distillation loss vs task loss
  beta: 0.3         # Weight for task loss
  
  # Data configuration (matching pretraining exactly)
  max_audio_length: 40000
  sample_rate: 16000
  mask_length: 10
  mask_prob: 0.08
  
  # Performance optimization - Resource-focused (matching pretraining)
  gradient_accumulation_steps: 2  # Reduced since we increased batch_size (matching pretraining)
  mixed_precision: true
  pin_memory: true  # Enabled for better GPU performance (matching pretraining)
  num_workers: 16  # Increased for better CPU utilization (16 cores available, matching pretraining)
  
  # Memory optimization (matching pretraining)
  gradient_checkpointing: true  # Enable to trade compute for memory
  use_cache: false  # Disable KV cache to save memory
  
  # Federated learning (matching pretraining)
  num_rounds: 1  # Reduced to match pretraining for consistency
  min_fit_clients: 2
  min_evaluate_clients: 3
  min_available_clients: 2
  fraction_fit: 1.0
  fraction_evaluate: 1.0

data:
  dataset_name: 'librispeech'
  subset: ['train-clean-100', 'train-clean-360', 'train-other-500']
  partition_method: 'speaker_based'
  iid_distribution: false
  test_split: 0.1
  validation_split: 0.1
  partitioned_data_root: '/home/saadan/scratch/federated_librispeech/src/federated_librispeech/data'  # Updated to match pretraining
  
  # Data loading optimization - Resource-focused (matching pretraining)
  dataloader:
    num_workers: 16  # Increased for better CPU utilization (16 cores available, matching pretraining)
    pin_memory: true  # Enabled for better GPU performance (matching pretraining)
    prefetch_factor: 8  # Increased for better data loading (matching pretraining)
    drop_last: true
    shuffle: true

strategy:
  fraction_fit: 1.0
  fraction_evaluate: 1.0
  min_fit_clients: 2
  min_evaluate_clients: 2
  min_available_clients: 2

server:
  aggregation:
    weighted_averaging: true
    clip_norm: 1.0
  
  early_stopping:
    enabled: true
    monitor: 'eval_distillation_loss'
    patience: 2  # Reduced to match pretraining
    min_delta: 0.001

client:
  enable_gpu: true
  max_memory_usage: '16GB'  # Increased for better performance (matching pretraining)
  mixed_precision: true  # Enable for memory efficiency (matching pretraining)
  evaluate_locally: true
  evaluation_fraction: 0.1
  
  local_config:
    batch_size: 16  # Increased to match pretraining.batch_size
    epochs: 1  # Reduced to match pretraining
    shuffle: true
    drop_last: true

checkpointing:
  # Checkpoint management strategy (matching pretraining exactly):
  # - Always saves latest model (latest_state.pt)
  # - Saves best model based on validation loss (best_state.pt)
  # - Saves round-specific checkpoints (round_XXX_state.pt)
  # - Keeps exactly 3 checkpoints: best, current round, and previous round
  save_dir: '/home/saadan/scratch/federated_librispeech/src/checkpoints/distillation'
  save_latest: true          # Always save latest model
  save_best: true            # Save best model based on validation loss
  save_best_round: true      # Save checkpoint for each round
  cleanup_old: true          # Remove old round checkpoints
  max_checkpoints: 3         # Keep exactly 3 checkpoints: best, current, previous

logging:
  log_dir: 'logs/distillation'
  client_log_dir: 'logs/distillation/clients'
  server_log_dir: 'logs/distillation/server'
  log_level: 'WARNING'  # Reduced from INFO to WARNING for performance (matching pretraining)
  client_log_level: 'WARNING'  # Reduced from INFO to WARNING for performance (matching pretraining)
  server_log_level: 'WARNING'  # Reduced from INFO to WARNING for performance (matching pretraining)
  save_metrics_to_file: true
  metrics_file: 'logs/distillation/federated_distillation_metrics.json'
  log_metrics_every_n_steps: 20  # Increased from 2 to 20 for performance (matching pretraining)

simulation:
  num_supernodes: 2
