# Optimized Federated HuBERT Pretraining Configuration
pretraining:
  # Model configuration
  hidden_size: 768
  intermediate_size: 3072
  num_attention_heads: 12
  num_hidden_layers: 12
  vocab_size: 504
  
  # Training configuration - Reduced for memory efficiency
  batch_size: 8  # Increased from 2 for better training efficiency
  local_epochs: 20
  learning_rate: 5e-4
  weight_decay: 0.01
  max_grad_norm: 1.0
  
  # Data configuration
  max_audio_length: 40000
  sample_rate: 16000
  mask_length: 10
  mask_prob: 0.08
  
  # Performance optimization - Memory-focused
  gradient_accumulation_steps: 4  # Reduced from 8 since we increased batch_size
  mixed_precision: true
  pin_memory: false  # Disabled to save memory
  num_workers: 8  # Reduced from 16 to save memory
  
  # Memory optimization
  gradient_checkpointing: true  # Enable to trade compute for memory
  use_cache: false  # Disable KV cache to save memory
  
  # Federated learning
  num_rounds: 100
  min_fit_clients: 10
  min_evaluate_clients: 10
  min_available_clients: 10
  fraction_fit: 1.0
  fraction_evaluate: 1.0

data:
  dataset_name: 'librispeech'
  subset: ['train-clean-100', 'train-clean-360', 'train-other-500']
  partition_method: 'speaker_based'
  iid_distribution: false
  test_split: 0.1
  validation_split: 0.1
  partitioned_data_root: '/home/saadan/scratch/federated_librispeech/src/federated_librispeech/data'
  
  # Data loading optimization - Memory-focused
  dataloader:
    num_workers: 8 # Reduced from 16
    pin_memory: false  # Disabled to save memory
    prefetch_factor: 1  # Reduced from 2
    drop_last: true
    shuffle: true

server:
  aggregation:
    weighted_averaging: true
    clip_norm: 1.0
  
  early_stopping:
    enabled: true
    monitor: 'eval_pretrain_loss'
    patience: 2
    min_delta: 0.001

client:
  enable_gpu: true
  max_memory_usage: '4GB'  # Reduced from 4GB
  mixed_precision: true  # Enable for memory efficiency
  evaluate_locally: true
  evaluation_fraction: 0.1
  
  local_config:
    batch_size: 8  # Increased from 1 to match pretraining.batch_size
    epochs: 20
    shuffle: true
    drop_last: true

logging:
  log_dir: '/home/saadan/scratch/federated_librispeech/src/logs/pretraining'
  client_log_dir: '/home/saadan/scratch/federated_librispeech/src/logs/pretraining/clients'
  server_log_dir: '/home/saadan/scratch/federated_librispeech/src/logs/pretraining/server'
  log_level: 'INFO'
  client_log_level: 'INFO'
  server_log_level: 'INFO'
  save_metrics_to_file: true
  metrics_file: '/home/saadan/scratch/federated_librispeech/src/logs/pretraining/federated_pretraining_metrics.json'
  log_metrics_every_n_steps: 5

simulation:
  num_supernodes: 10

# Checkpointing configuration
checkpointing:
  save_dir: '/home/saadan/scratch/federated_librispeech/src/checkpoints/pretraining'
  save_latest: true          # Always save latest model
  save_best: true            # Save best model based on validation loss
  save_best_round: true      # Save checkpoint for the best round
  cleanup_old: true          # Remove old round checkpoints
  max_checkpoints: 5         # Maximum number of checkpoints to keep (increased from 3)
