# Optimized Federated HuBERT Pretraining Configuration
pretraining:
  # Model configuration
  hidden_size: 768
  intermediate_size: 3072
  num_attention_heads: 12
  num_hidden_layers: 12
  vocab_size: 504
  
  # Training configuration
  batch_size: 4  # Increased from 1
  local_epochs: 5
  learning_rate: 5e-4
  weight_decay: 0.01
  max_grad_norm: 1.0
  
  # Data configuration
  max_audio_length: 40000
  sample_rate: 16000
  mask_length: 10
  mask_prob: 0.08
  
  # Performance optimization
  gradient_accumulation_steps: 4
  mixed_precision: true
  pin_memory: true
  num_workers: 16
  
  # Federated learning
  num_rounds: 10
  min_fit_clients: 10
  min_evaluate_clients: 10
  min_available_clients: 10
  fraction_fit: 1.0
  fraction_evaluate: 1.0

data:
  dataset_name: 'librispeech'
  subset: ['train-clean-100', 'train-clean-360', 'train-other-500']
  partition_method: 'speaker_based'
  iid_distribution: false
  test_split: 0.1
  validation_split: 0.1
  partitioned_data_root: '/home/saadan/scratch/federated_librispeech/src/federated_librispeech/data'
  
  # Data loading optimization
  dataloader:
    num_workers: 16
    pin_memory: true
    prefetch_factor: 2
    drop_last: true
    shuffle: true

server:

  aggregation:
    weighted_averaging: true
    clip_norm: 1.0
  
  early_stopping:
    enabled: true
    monitor: 'eval_pretrain_loss'
    patience: 2
    min_delta: 0.001

client:
  enable_gpu: true
  max_memory_usage: '8GB'
  mixed_precision: false
  evaluate_locally: true
  evaluation_fraction: 0.1
  
  local_config:
    batch_size: 4
    epochs: 1
    shuffle: true
    drop_last: true

logging:
  log_dir: 'logs/pretraining'
  client_log_dir: 'logs/pretraining/clients'
  server_log_dir: 'logs/pretraining/server'
  log_level: 'INFO'
  client_log_level: 'INFO'
  server_log_level: 'INFO'
  save_metrics_to_file: true
  metrics_file: 'logs/pretraining/federated_pretraining_metrics.json'
  log_metrics_every_n_steps: 2

simulation:
  num_supernodes: 10
