runner:
  total_steps: 200000
  gradient_clipping: 1
  gradient_accumulate_steps: 4

  log_step: 50
  eval_step: 2000
  save_step: 2000
  max_keep: 2
  save_dir: /home/saadan/scratch/federated_librispeech/src/models/finetuned
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: AdamW
  lr: 1.0e-4
  weight_decay: 0.01

scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 500

downstream_expert:
  datarc:
    speech_commands_root: /lustre07/scratch/saadan/federated_librispeech/speech_commands
    speech_commands_test_root: /lustre07/scratch/saadan/federated_librispeech/speech_commands
    num_workers: 4
    batch_size: 16
    pin_memory: false
    prefetch_factor: 2

  modelrc:
    projector_dim: 256
    select: UtteranceLevel
    UtteranceLevel:
      pooling: MeanPooling